dbfilename redis_cache.rdb
dir /mnt/d/itucedric/L3/S6/Eval/02/vrai/config/pids
pidfile /mnt/d/itucedric/L3/S6/Eval/02/vrai/config/pids/redis_cache.pid
bind 127.0.0.1
port 13003
maxmemory 393mb
maxmemory-policy allkeys-lru
appendonly no

save ""


aclfile /mnt/d/itucedric/L3/S6/Eval/02/vrai/config/redis_cache.acl
