dbfilename redis_queue.rdb
dir /mnt/d/itucedric/L3/S6/Eval/02/vrai/config/pids
pidfile /mnt/d/itucedric/L3/S6/Eval/02/vrai/config/pids/redis_queue.pid
bind 127.0.0.1
port 11003

aclfile /mnt/d/itucedric/L3/S6/Eval/02/vrai/config/redis_queue.acl
